/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg5_felipelin;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author felipelinzhao
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
        jTabbedPane1.setEnabledAt(2, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        popup_lista = new javax.swing.JPopupMenu();
        lista_modificar_super = new javax.swing.JMenuItem();
        lista_eliminar_super = new javax.swing.JMenuItem();
        popup_arbol = new javax.swing.JPopupMenu();
        popup_lista2 = new javax.swing.JPopupMenu();
        lista_modificar_vil = new javax.swing.JMenuItem();
        lista_eliminar_vil = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tf_super_nom = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_super_poder = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_super_debil = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_super_f = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_super_a = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_super_m = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_super = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        tf_vil_nom = new javax.swing.JTextField();
        tf_vil_poder = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_vil_debil = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tf_vil_m = new javax.swing.JTextField();
        tf_vil_a = new javax.swing.JTextField();
        tf_vil_f = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_villano = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_squad_nom = new javax.swing.JTextField();
        tf_squad_base = new javax.swing.JTextField();
        rb_squad_vil = new javax.swing.JRadioButton();
        rb_squad_sup = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_squad1 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_squad2 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jt_squads = new javax.swing.JTree();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        lista_modificar_super.setText("jMenuItem1");
        lista_modificar_super.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lista_modificar_superActionPerformed(evt);
            }
        });
        popup_lista.add(lista_modificar_super);

        lista_eliminar_super.setText("jMenuItem2");
        lista_eliminar_super.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lista_eliminar_superActionPerformed(evt);
            }
        });
        popup_lista.add(lista_eliminar_super);

        lista_modificar_vil.setText("jMenuItem1");
        lista_modificar_vil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lista_modificar_vilActionPerformed(evt);
            }
        });
        popup_lista2.add(lista_modificar_vil);

        lista_eliminar_vil.setText("jMenuItem2");
        lista_eliminar_vil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lista_eliminar_vilActionPerformed(evt);
            }
        });
        popup_lista2.add(lista_eliminar_vil);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Nombre");

        jLabel6.setText("Poder");

        jLabel7.setText("Debilidad");

        jLabel8.setText("Fuerza");

        jLabel9.setText("Agilidad Fisica");

        jLabel10.setText("Agilidad Mental");

        jButton2.setText("Crear");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jl_super.setModel(new DefaultListModel());
        jl_super.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_superMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jl_super);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_super_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_super_f, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_super_poder, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_super_debil, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_super_a, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_super_m, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 291, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(265, 265, 265))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(323, 323, 323))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_super_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_super_f, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_super_poder, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_super_a, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_super_debil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_super_m, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addGap(63, 63, 63))
        );

        jTabbedPane1.addTab("Crear Super Heroe", jPanel2);

        jLabel11.setText("Poder");

        jLabel12.setText("Nombre");

        jLabel13.setText("Debilidad");

        jLabel14.setText("Fuerza");

        jLabel15.setText("Agilidad Fisica");

        jLabel16.setText("Agilidad Mental");

        jButton3.setText("Crear");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jl_villano.setModel(new DefaultListModel());
        jl_villano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_villanoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jl_villano);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_vil_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_vil_f, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_vil_poder, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_vil_debil, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 341, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_vil_a, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_vil_m, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(327, 327, 327))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(276, 276, 276))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_vil_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_vil_f, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_vil_poder, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_vil_a, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_vil_debil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_vil_m, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("Crear Villano", jPanel3);

        jLabel1.setText("Nombre");

        jLabel3.setText("Tipo");

        jLabel4.setText("Base");

        buttonGroup1.add(rb_squad_vil);
        rb_squad_vil.setSelected(true);
        rb_squad_vil.setText("Villano");

        buttonGroup1.add(rb_squad_sup);
        rb_squad_sup.setText("SuperHeroe");

        jButton1.setText("Crear");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jl_squad1.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jl_squad1);

        jl_squad2.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(jl_squad2);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Escuadrones");
        jt_squads.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane5.setViewportView(jt_squads);

        jLabel17.setText("SuperHeroe");

        jLabel18.setText("Villano");

        jLabel2.setText("Arbol");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(tf_squad_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(135, 135, 135)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(tf_squad_base, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(130, 130, 130)
                                        .addComponent(rb_squad_vil)
                                        .addGap(9, 9, 9)
                                        .addComponent(rb_squad_sup))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel17)
                                .addGap(142, 142, 142)
                                .addComponent(jLabel18)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_squad_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_squad_base, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb_squad_vil)
                                    .addComponent(rb_squad_sup)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Crear Escuadron", jPanel1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 801, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab4", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String nombre, base, tipo = "";
        String c = "", confirm = "s", t = "";
        DefaultMutableTreeNode nodo_persona = new DefaultMutableTreeNode();
        DefaultMutableTreeNode nodo_lider = new DefaultMutableTreeNode();
        DefaultMutableTreeNode nodo_poder = new DefaultMutableTreeNode();
        DefaultMutableTreeNode nodo_poderL = new DefaultMutableTreeNode();
        DefaultTreeModel modelo_arbol = (DefaultTreeModel) jt_squads.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo_arbol.getRoot();
        DefaultMutableTreeNode nodo_escuadron;
        Heroe lider = new Heroe();
        try {

            if (rb_squad_sup.isSelected()) {
                tipo = "SuperHeroe";

            } else if (rb_squad_vil.isSelected()) {

                tipo = "Villano";

            } else {
                JOptionPane.showMessageDialog(this, "error1");
            }

            switch (tipo) {
                case "SuperHeroe": {
                    for (SuperHeroe su : squad1) {
                        t += squad1.indexOf(su) + " ";
                        t += su;
                        t += "\n";

                    }
                    int pos2 = Integer.parseInt(JOptionPane.showInputDialog(this, t + "\nIngrese la posicion del super heroe que quiere hacer lider"));
                    lider = squad1.get(pos2);
                    nodo_lider = new DefaultMutableTreeNode(squad1.get(pos2));
                    nodo_poderL = new DefaultMutableTreeNode(squad1.get(pos2).getPoder());
                    squad1.remove(pos2);
                    break;
                }
                case "Villano": {
                    for (Villano su : squad2) {
                        t += squad2.indexOf(su) + " ";
                        t += su;
                        t += "\n";

                    }
                    int pos2 = Integer.parseInt(JOptionPane.showInputDialog(this, t + "\nIngrese la posicion del villano que quiere hacer lider"));
                    lider = squad2.get(pos2);
                    nodo_lider = new DefaultMutableTreeNode(squad1.get(pos2));
                    nodo_poderL = new DefaultMutableTreeNode(squad1.get(pos2).getDeblilidad());

                    squad2.remove(pos2);
                    break;
                }
                default:
                    JOptionPane.showMessageDialog(this, "error2");
                    break;
            }

            base = tf_squad_base.getText();
            nombre = tf_squad_nom.getText();
            nodo_escuadron = new DefaultMutableTreeNode(new Escuadrones(nombre, base, lider, tipo));
            squad.add(new Escuadrones(nombre, base, lider, tipo));

            DefaultListModel modelo1 = (DefaultListModel) jl_squad1.getModel();
            DefaultListModel modelo2 = (DefaultListModel) jl_squad2.getModel();

            switch (tipo) {
                case "SuperHeroe":
                    for (SuperHeroe su : squad1) {
                        c += squad1.indexOf(su) + " ";
                        c += su;
                        c += "\n";

                    }
                    while ("s".equals(confirm)) {

                        int pos = Integer.parseInt(JOptionPane.showInputDialog(this, c + "\nIngrese la posicion del super heroe que quiere agregar"));
                        ((Escuadrones) squad.get(lista1)).getLista().add(squad1.get(pos));
                        confirm = JOptionPane.showInputDialog(this, "Quiere agregar otro superheroe? [s/n]");
                        nodo_persona = new DefaultMutableTreeNode(((Escuadrones) squad.get(lista1)).getLista().get(pos));
                        nodo_poder = new DefaultMutableTreeNode(((Escuadrones) squad.get(lista1)).getLista().get(lista1).getPoder());
                        nodo_persona.add(nodo_poder);
                        nodo_escuadron.add(nodo_persona);

                    }
                    modelo1.addElement(new Escuadrones(nombre, base, lider, tipo));
                    jl_squad1.setModel(modelo1);
                    break;
                case "Villano":
                    for (Villano su : squad2) {
                        c += squad2.indexOf(su) + " ";
                        c += su;
                        c += "\n";

                    }
                    while ("s".equals(confirm)) {

                        int pos = Integer.parseInt(JOptionPane.showInputDialog(this, c + "\nIngrese la posicion del villano que quiere agregar"));
                        ((Escuadrones) squad.get(lista1)).getLista().add(squad2.get(pos));
                        JOptionPane.showInputDialog(this, c + "\nIngrese la posicion del villano que quiere agregar");
                        nodo_persona = new DefaultMutableTreeNode(((Escuadrones) squad.get(lista1)).getLista().add(squad1.get(pos)));
                        nodo_poder = new DefaultMutableTreeNode(((Escuadrones) squad.get(lista1)).getLista().get(lista1).getDeblilidad());
                        nodo_persona.add(nodo_poder);
                        nodo_escuadron.add(nodo_persona);

                    }
                    modelo2.addElement(new Escuadrones(nombre, base, lider, tipo));
                    jl_squad2.setModel(modelo2);
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "error3");
                    break;
            }

            JOptionPane.showMessageDialog(this, "Agrego con exito el escuadron");
            tf_squad_base.setText("");
            tf_squad_nom.setText("");
            nodo_lider.add(nodo_poderL);
            nodo_escuadron.add(nodo_lider);
            raiz.add(nodo_escuadron);
            modelo_arbol.reload();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error!");
        }

        lista1++;
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        String nombre, poder, debilidad;
        int fuerza, agilidad, mente;
        int suma;
        try {
            fuerza = Integer.parseInt(tf_super_f.getText());
            agilidad = Integer.parseInt(tf_super_a.getText());
            mente = Integer.parseInt(tf_super_m.getText());

            suma = fuerza + agilidad + mente;

            if (suma == 100) {
                nombre = tf_super_nom.getText();
                poder = tf_super_poder.getText();
                debilidad = tf_super_debil.getText();

                DefaultListModel modelo = (DefaultListModel) jl_super.getModel();

                modelo.addElement(new SuperHeroe(nombre, poder, debilidad, new Escuadrones(), fuerza, agilidad, mente));

                jl_super.setModel(modelo);

                squad1.add(new SuperHeroe(nombre, poder, debilidad, new Escuadrones(), fuerza, agilidad, mente));
                JOptionPane.showMessageDialog(this, "Su super heroe fue agregado con exito!");
                tf_super_a.setText("");
                tf_super_debil.setText("");
                tf_super_f.setText("");
                tf_super_m.setText("");
                tf_super_nom.setText("");
                tf_super_poder.setText("");
                jTabbedPane1.setEnabledAt(2, true);

            } else {
                JOptionPane.showMessageDialog(this, "Sus stats no tienen la suma de 100!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error!");
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        String nombre, poder, debilidad;
        int fuerza, agilidad, mente;
        int suma;
        try {
            fuerza = Integer.parseInt(tf_vil_f.getText());
            agilidad = Integer.parseInt(tf_vil_a.getText());
            mente = Integer.parseInt(tf_vil_m.getText());

            suma = fuerza + agilidad + mente;

            if (suma == 100) {
                nombre = tf_vil_nom.getText();
                poder = tf_vil_poder.getText();
                debilidad = tf_vil_debil.getText();

                squad2.add(new Villano(nombre, poder, debilidad, new Escuadrones(), fuerza, agilidad, mente));

                DefaultListModel modelo = (DefaultListModel) jl_villano.getModel();

                modelo.addElement(new Villano(nombre, poder, debilidad, new Escuadrones(), fuerza, agilidad, mente));

                jl_villano.setModel(modelo);

                JOptionPane.showMessageDialog(this, "Su villano fue agregado con exito!");

                tf_vil_a.setText("");
                tf_vil_debil.setText("");
                tf_vil_f.setText("");
                tf_vil_m.setText("");
                tf_vil_nom.setText("");
                tf_vil_poder.setText("");

                jTabbedPane1.setEnabledAt(2, true);

            } else {
                JOptionPane.showMessageDialog(this, "Sus stats no tienen la suma de 100!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error!");
        }

    }//GEN-LAST:event_jButton3MouseClicked

    private void jl_superMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_superMouseClicked
        // TODO add your handling code here:
        if (jl_super.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                popup_lista.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jl_superMouseClicked

    private void lista_eliminar_superActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lista_eliminar_superActionPerformed
        // TODO add your handling code here:
        if (jl_super.getSelectedIndex() >= 0) {
            DefaultListModel modelo = (DefaultListModel) jl_super.getModel();

            modelo.remove(jl_super.getSelectedIndex());

            jl_super.setModel(modelo);
        }
    }//GEN-LAST:event_lista_eliminar_superActionPerformed

    private void lista_modificar_superActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lista_modificar_superActionPerformed
        // TODO add your handling code here:
        if (jl_super.getSelectedIndex() >= 0) {
            DefaultListModel modelo = (DefaultListModel) jl_super.getModel();

            ((SuperHeroe) modelo.get(jl_super.getSelectedIndex())).setNombre(JOptionPane.showInputDialog("Ingrese el nuevo nombre"));
            ((SuperHeroe) modelo.get(jl_super.getSelectedIndex())).setPoder(JOptionPane.showInputDialog("Ingrese el nuevo poder"));
            ((SuperHeroe) modelo.get(jl_super.getSelectedIndex())).setDeblilidad(JOptionPane.showInputDialog("Ingrese la nueva debilidad"));
            ((SuperHeroe) modelo.get(jl_super.getSelectedIndex())).setFuerza(Integer.parseInt(JOptionPane.showInputDialog("Ingrese la nueva fuerza")));
            ((SuperHeroe) modelo.get(jl_super.getSelectedIndex())).setAgilidad(Integer.parseInt(JOptionPane.showInputDialog("Ingrese la nueva agilidad fisica")));
            ((SuperHeroe) modelo.get(jl_super.getSelectedIndex())).setMente(Integer.parseInt(JOptionPane.showInputDialog("Ingrese la nueva agilidad mental")));

            jl_super.setModel(modelo);

        }
    }//GEN-LAST:event_lista_modificar_superActionPerformed

    private void lista_eliminar_vilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lista_eliminar_vilActionPerformed
        // TODO add your handling code here:
          if (jl_villano.getSelectedIndex() >= 0) {
            DefaultListModel modelo = (DefaultListModel) jl_villano.getModel();

            modelo.remove(jl_villano.getSelectedIndex());

            jl_villano.setModel(modelo);
        }
    }//GEN-LAST:event_lista_eliminar_vilActionPerformed

    private void lista_modificar_vilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lista_modificar_vilActionPerformed
        // TODO add your handling code here:
        if (jl_villano.getSelectedIndex() >= 0) {
            DefaultListModel modelo = (DefaultListModel) jl_villano.getModel();

            ((Villano) modelo.get(jl_villano.getSelectedIndex())).setNombre(JOptionPane.showInputDialog("Ingrese el nuevo nombre"));
            ((Villano) modelo.get(jl_villano.getSelectedIndex())).setPoder(JOptionPane.showInputDialog("Ingrese el nuevo poder"));
            ((Villano) modelo.get(jl_villano.getSelectedIndex())).setDeblilidad(JOptionPane.showInputDialog("Ingrese la nueva debilidad"));
            ((Villano) modelo.get(jl_villano.getSelectedIndex())).setFuerza(Integer.parseInt(JOptionPane.showInputDialog("Ingrese la nueva fuerza")));
            ((Villano) modelo.get(jl_villano.getSelectedIndex())).setAgilidad(Integer.parseInt(JOptionPane.showInputDialog("Ingrese la nueva agilidad fisica")));
            ((Villano) modelo.get(jl_villano.getSelectedIndex())).setMente(Integer.parseInt(JOptionPane.showInputDialog("Ingrese la nueva agilidad mental")));

            jl_villano.setModel(modelo);

        }
    }//GEN-LAST:event_lista_modificar_vilActionPerformed

    private void jl_villanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_villanoMouseClicked
        // TODO add your handling code here:
        if (jl_villano.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                popup_lista2.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jl_villanoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> jl_squad1;
    private javax.swing.JList<String> jl_squad2;
    private javax.swing.JList<String> jl_super;
    private javax.swing.JList<String> jl_villano;
    private javax.swing.JTree jt_squads;
    private javax.swing.JMenuItem lista_eliminar_super;
    private javax.swing.JMenuItem lista_eliminar_vil;
    private javax.swing.JMenuItem lista_modificar_super;
    private javax.swing.JMenuItem lista_modificar_vil;
    private javax.swing.JPopupMenu popup_arbol;
    private javax.swing.JPopupMenu popup_lista;
    private javax.swing.JPopupMenu popup_lista2;
    private javax.swing.JRadioButton rb_squad_sup;
    private javax.swing.JRadioButton rb_squad_vil;
    private javax.swing.JTextField tf_squad_base;
    private javax.swing.JTextField tf_squad_nom;
    private javax.swing.JTextField tf_super_a;
    private javax.swing.JTextField tf_super_debil;
    private javax.swing.JTextField tf_super_f;
    private javax.swing.JTextField tf_super_m;
    private javax.swing.JTextField tf_super_nom;
    private javax.swing.JTextField tf_super_poder;
    private javax.swing.JTextField tf_vil_a;
    private javax.swing.JTextField tf_vil_debil;
    private javax.swing.JTextField tf_vil_f;
    private javax.swing.JTextField tf_vil_m;
    private javax.swing.JTextField tf_vil_nom;
    private javax.swing.JTextField tf_vil_poder;
    // End of variables declaration//GEN-END:variables
    ArrayList<Heroe> squad = new ArrayList();
    ArrayList<SuperHeroe> squad1 = new ArrayList();
    ArrayList<Villano> squad2 = new ArrayList();
    int lista1 = 0, lista2;
}
